version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=geoposition
      - POSTGRES_DB=converterdb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    external: false